<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>TourVerse — AI Travel Planner</title>
  <meta name="description" content="Plan your perfect trip with AI-powered itineraries generated by IBM watsonx.ai Granite models." />
  <!-- Bootstrap 5 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
  <!-- Font Awesome 6 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
  <!-- Custom CSS -->
  <link rel="stylesheet" href="assets/css/style.css" />
</head>

<body class="index-page">

  <!-- ── NAVBAR ─────────────────────────────────────────────────────────── -->
  <nav class="tp-navbar">
    <div class="container-fluid px-4 d-flex align-items-center justify-content-between" style="height:60px;">
      <a href="index.php" class="tp-brand">
        <span class="tp-brand-icon"><i class="fa-solid fa-map-location-dot"></i></span>
        <span class="tp-brand-name"><span> Tour</span>Verse</span>
      </a>
      <div class="d-flex align-items-center gap-2">
        <span class="tp-ibm-pill"><i class="fa-solid fa-atom"></i> IBM watsonx.ai</span>
        <button class="tp-icon-btn" id="themeToggle" title="Toggle theme">
          <i class="fa-solid fa-moon"></i>
        </button>
      </div>
    </div>
  </nav>

  <!-- ── HERO ───────────────────────────────────────────────────────────── -->
  <section class="tp-hero">
    <div class="tp-hero-bg">
      <div class="tp-orb tp-orb-1"></div>
      <div class="tp-orb tp-orb-2"></div>
      <div class="tp-orb tp-orb-3"></div>
    </div>
    <div class="container position-relative">
      <div class="row justify-content-center text-center">
        <div class="col-lg-7">
          <div class="tp-hero-badge"><i class="fa-solid fa-sparkles"></i> IBM watsonx.ai Granite</div>
          <h1 class="tp-hero-title">Your AI Travel<br><span class="tp-gradient-text">Companion</span></h1>
          <p class="tp-hero-sub">Personalised day-wise itineraries, budget breakdowns, live weather &amp; interactive maps — generated in seconds.</p>
          <div class="tp-feature-pills">
            <span><i class="fa-solid fa-calendar-days"></i> Day-wise Plans</span>
            <span><i class="fa-solid fa-indian-rupee-sign"></i> Budget Analysis</span>
            <span><i class="fa-solid fa-cloud-sun"></i> Live Weather</span>
            <span><i class="fa-solid fa-map-location-dot"></i> Interactive Map</span>
            <span><i class="fa-solid fa-file-pdf"></i> PDF Export</span>
            <span><i class="fa-solid fa-envelope"></i> Email Itinerary</span>
          </div>
          <a href="#plannerForm" class="tp-cta-btn"><i class="fa-solid fa-wand-magic-sparkles"></i> Start Planning Free</a>
        </div>
      </div>
    </div>
  </section>

  <!-- ── PLANNER FORM ───────────────────────────────────────────────────── -->
  <section id="plannerForm" class="tp-form-section">
    <div class="container py-5">

      <div class="tp-form-header text-center mb-4">
        <h2 class="tp-section-title">Plan Your <span class="tp-gradient-text">Dream Trip</span></h2>
        <p class="tp-section-sub">Fill in your travel details and let Granite AI craft the perfect itinerary</p>
      </div>

      <!-- Stepper indicator -->
      <div class="tp-stepper mb-4">
        <div class="tp-step active" data-step="1"><span>1</span> Destination</div>
        <div class="tp-step-line"></div>
        <div class="tp-step" data-step="2"><span>2</span> Travellers</div>
        <div class="tp-step-line"></div>
        <div class="tp-step" data-step="3"><span>3</span> Budget</div>
        <div class="tp-step-line"></div>
        <div class="tp-step" data-step="4"><span>4</span> Preferences</div>
      </div>

      <form id="travelForm" novalidate>

        <!-- STEP 1 — Destination & Dates -->
        <div class="tp-form-step active" id="formStep1">
          <div class="tp-card tp-form-card">
            <div class="tp-card-title"><span class="tp-step-dot">1</span> Destination &amp; Dates</div>
            <div class="row g-3 mt-1">
              <div class="col-md-6">
                <label class="tp-label"><i class="fa-solid fa-location-dot"></i> Destination *</label>
                <div class="tp-input-wrap">
                  <input type="text" class="tp-input" id="destination" name="destination"
                    placeholder="e.g., Goa, Paris, Bali, Jaipur" required autocomplete="off" />
                  <i class="fa-solid fa-magnifying-glass tp-input-icon"></i>
                </div>
                <div class="tp-invalid">Please enter your destination.</div>
              </div>
              <div class="col-md-6">
                <label class="tp-label"><i class="fa-solid fa-plane-up"></i> Travelling From</label>
                <input type="text" class="tp-input" id="origin" name="origin"
                  placeholder="e.g., Mumbai, Delhi, Bengaluru" />
              </div>
              <div class="col-md-6">
                <label class="tp-label"><i class="fa-solid fa-calendar-plus"></i> Start Date *</label>
                <input type="date" class="tp-input" id="startDate" name="start_date" required />
                <div class="tp-invalid">Please select a start date.</div>
              </div>
              <div class="col-md-6">
                <label class="tp-label"><i class="fa-solid fa-calendar-check"></i> End Date *</label>
                <input type="date" class="tp-input" id="endDate" name="end_date" required />
                <div class="tp-invalid">Please select an end date (after start date).</div>
              </div>
            </div>
            <div class="tp-step-actions mt-4">
              <button type="button" class="tp-btn-next" onclick="stepNext(1)">Next <i class="fa-solid fa-arrow-right"></i></button>
            </div>
          </div>
        </div>

        <!-- STEP 2 — Travellers & Type -->
        <div class="tp-form-step" id="formStep2">
          <div class="tp-card tp-form-card">
            <div class="tp-card-title"><span class="tp-step-dot">2</span> Travellers &amp; Trip Type</div>
            <div class="row g-3 mt-1">
              <div class="col-md-4">
                <label class="tp-label"><i class="fa-solid fa-users"></i> No. of Travellers *</label>
                <input type="number" class="tp-input" id="travellers" name="travellers"
                  min="1" max="50" value="2" required />
              </div>
              <div class="col-md-8">
                <label class="tp-label"><i class="fa-solid fa-id-badge"></i> Travel Type *</label>
                <div class="tp-pill-selector" id="travelTypeSelector">
                  <input type="hidden" id="travelType" name="travel_type" value="Couple" />
                  <button type="button" class="tp-pill" data-value="Solo">🧍 Solo</button>
                  <button type="button" class="tp-pill active" data-value="Couple">💑 Couple</button>
                  <button type="button" class="tp-pill" data-value="Family">👨‍👩‍👧 Family</button>
                  <button type="button" class="tp-pill" data-value="Group">👥 Group</button>
                  <button type="button" class="tp-pill" data-value="Business">💼 Business</button>
                </div>
              </div>
            </div>
            <div class="tp-step-actions mt-4">
              <button type="button" class="tp-btn-back" onclick="stepBack(2)"><i class="fa-solid fa-arrow-left"></i> Back</button>
              <button type="button" class="tp-btn-next" onclick="stepNext(2)">Next <i class="fa-solid fa-arrow-right"></i></button>
            </div>
          </div>
        </div>

        <!-- STEP 3 — Budget -->
        <div class="tp-form-step" id="formStep3">
          <div class="tp-card tp-form-card">
            <div class="tp-card-title"><span class="tp-step-dot">3</span> Budget &amp; Currency</div>
            <div class="row g-3 mt-1">
              <div class="col-12">
                <label class="tp-label"><i class="fa-solid fa-coins"></i> Budget Category *</label>
                <div class="tp-budget-grid" id="budgetSelector">
                  <input type="hidden" id="budgetType" name="budget" value="Mid-range" />
                  <div class="tp-budget-card" data-value="Budget">
                    <div class="tp-budget-icon">🪙</div>
                    <div class="tp-budget-name">Budget</div>
                    <div class="tp-budget-sub">Backpacker friendly</div>
                  </div>
                  <div class="tp-budget-card active" data-value="Mid-range">
                    <div class="tp-budget-icon">💳</div>
                    <div class="tp-budget-name">Mid-range</div>
                    <div class="tp-budget-sub">Comfort &amp; value</div>
                  </div>
                  <div class="tp-budget-card" data-value="Luxury">
                    <div class="tp-budget-icon">💎</div>
                    <div class="tp-budget-name">Luxury</div>
                    <div class="tp-budget-sub">Premium experience</div>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <label class="tp-label"><i class="fa-solid fa-calculator"></i> Estimated Budget</label>
                <input type="number" class="tp-input" id="budgetAmount" name="budget_amount"
                  placeholder="e.g., 50000" min="0" />
              </div>
              <div class="col-md-6">
                <label class="tp-label"><i class="fa-solid fa-money-bill-transfer"></i> Currency</label>
                <select class="tp-input" id="currency" name="currency">
                  <option value="INR" selected>🇮🇳 INR — Indian Rupee</option>
                  <option value="USD">🇺🇸 USD — US Dollar</option>
                  <option value="EUR">🇪🇺 EUR — Euro</option>
                  <option value="GBP">🇬🇧 GBP — British Pound</option>
                  <option value="AED">🇦🇪 AED — UAE Dirham</option>
                  <option value="SGD">🇸🇬 SGD — Singapore Dollar</option>
                  <option value="THB">🇹🇭 THB — Thai Baht</option>
                  <option value="JPY">🇯🇵 JPY — Japanese Yen</option>
                  <option value="AUD">🇦🇺 AUD — Australian Dollar</option>
                </select>
              </div>
            </div>
            <div class="tp-step-actions mt-4">
              <button type="button" class="tp-btn-back" onclick="stepBack(3)"><i class="fa-solid fa-arrow-left"></i> Back</button>
              <button type="button" class="tp-btn-next" onclick="stepNext(3)">Next <i class="fa-solid fa-arrow-right"></i></button>
            </div>
          </div>
        </div>

        <!-- STEP 4 — Preferences -->
        <div class="tp-form-step" id="formStep4">
          <div class="tp-card tp-form-card">
            <div class="tp-card-title"><span class="tp-step-dot">4</span> Interests &amp; Preferences</div>
            <div class="row g-3 mt-1">
              <div class="col-12">
                <label class="tp-label"><i class="fa-solid fa-heart"></i> Travel Interests</label>
                <div class="tp-interest-grid" id="interestsGrid">
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Culture & Heritage" checked /><span>🏛️ Culture</span></label>
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Adventure & Trekking" /><span>🧗 Adventure</span></label>
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Beach & Water Sports" /><span>🏖️ Beach</span></label>
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Food & Culinary" checked /><span>🍜 Food</span></label>
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Wildlife & Nature" /><span>🦁 Wildlife</span></label>
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Shopping & Markets" /><span>🛍️ Shopping</span></label>
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Spiritual & Religious" /><span>🛕 Spiritual</span></label>
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Photography & Art" /><span>📸 Photo</span></label>
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Nightlife & Entertainment" /><span>🎭 Nightlife</span></label>
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Wellness & Spa" /><span>🧘 Wellness</span></label>
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Sports & Recreation" /><span>⚽ Sports</span></label>
                  <label class="tp-interest"><input type="checkbox" name="interests[]" value="Eco Tourism" /><span>🌿 Eco</span></label>
                </div>
              </div>
              <div class="col-md-4">
                <label class="tp-label"><i class="fa-solid fa-utensils"></i> Dietary Preference</label>
                <select class="tp-input" id="diet" name="diet">
                  <option value="No preference">🍽️ No Preference</option>
                  <option value="Vegetarian">🥦 Vegetarian</option>
                  <option value="Vegan">🌱 Vegan</option>
                  <option value="Jain">🙏 Jain</option>
                  <option value="Halal">☪️ Halal</option>
                  <option value="Non-vegetarian">🍗 Non-Vegetarian</option>
                  <option value="Gluten-free">🌾 Gluten-Free</option>
                </select>
              </div>
              <div class="col-md-4">
                <label class="tp-label"><i class="fa-solid fa-wheelchair"></i> Accessibility</label>
                <select class="tp-input" id="mobility" name="mobility">
                  <option value="No restrictions">✅ No Restrictions</option>
                  <option value="Wheelchair accessible">♿ Wheelchair</option>
                  <option value="Limited walking">🦯 Limited Walking</option>
                  <option value="Elderly traveller">👴 Elderly</option>
                  <option value="Travelling with infants">👶 With Infants</option>
                </select>
              </div>
              <div class="col-md-4">
                <label class="tp-label"><i class="fa-solid fa-language"></i> Language</label>
                <select class="tp-input" id="language" name="language">
                  <option value="English" selected>🇬🇧 English</option>
                  <option value="Hindi">🇮🇳 Hindi</option>
                  <option value="French">🇫🇷 French</option>
                  <option value="Spanish">🇪🇸 Spanish</option>
                  <option value="German">🇩🇪 German</option>
                  <option value="Japanese">🇯🇵 Japanese</option>
                </select>
              </div>
              <div class="col-12">
                <label class="tp-label"><i class="fa-solid fa-comment-dots"></i> Special Requirements</label>
                <textarea class="tp-input" id="specialReq" name="special_req" rows="2"
                  placeholder="e.g., celebrating anniversary, wheelchair access, travelling with pets…"></textarea>
              </div>
            </div>
            <div class="tp-step-actions mt-4">
              <button type="button" class="tp-btn-back" onclick="stepBack(4)"><i class="fa-solid fa-arrow-left"></i> Back</button>
              <button type="submit" class="tp-generate-btn" id="generateBtn">
                <span class="btn-content"><i class="fa-solid fa-wand-magic-sparkles"></i> Generate AI Itinerary</span>
                <span class="btn-loading d-none"><span class="tp-spinner"></span> Crafting your itinerary…</span>
              </button>
            </div>
          </div>
        </div>

      </form>

      <p class="text-center tp-trust-line mt-3">
        <i class="fa-solid fa-shield-halved"></i> No login required &nbsp;·&nbsp; No data stored &nbsp;·&nbsp; Powered by IBM Granite
      </p>
    </div>
  </section>

  <!-- ── FOOTER ─────────────────────────────────────────────────────────── -->
  <footer class="tp-footer">
    <div class="tp-footer-inner">

      <!-- ── TWO-COLUMN TOP AREA ──────────────────────────────────────────── -->
      <div class="tp-footer-top">

        <!-- Left: logo + description + IBM badge -->
        <div class="tp-footer-left">
          <div class="tp-footer-brand">
            <div class="tp-footer-brand-icon"><i class="fa-solid fa-map-location-dot"></i></div>
            <span class="tp-footer-brand-name"><span>Tour</span>Verse</span>
          </div>
          <p class="tp-footer-tagline">
            AI-powered travel itineraries generated using IBM watsonx.ai Granite
          </p>
          <span class="tp-ibm-pill tp-ibm-sm">
            <i class="fa-solid fa-microchip"></i> IBM watsonx.ai Granite
          </span>
        </div>

        <!-- Right: developer info + social icons -->
        <div class="tp-footer-right">
          <div class="tp-footer-dev-label">Developer</div>
          <div class="tp-footer-dev-name">Harsh Rakeshkumar Champaneri</div>
          <div class="tp-footer-dev-title">Full-Stack Developer &nbsp;|&nbsp; AI Enthusiast</div>
          <div class="tp-footer-social">
            <a href="https://www.linkedin.com/in/harsh-rakeshkumar-champaneri-a04523315?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
              target="_blank" rel="noopener" class="tp-footer-social-link linkedin" title="LinkedIn">
              <i class="fa-brands fa-linkedin-in"></i>
            </a>
            <a href="https://github.com/harsh-champaneri"
              target="_blank" rel="noopener" class="tp-footer-social-link github" title="GitHub">
              <i class="fa-brands fa-github"></i>
            </a>
            <a href="mailto:champharsh.2005@gmail.com"
              class="tp-footer-social-link email" title="Email">
              <i class="fa-solid fa-envelope"></i>
            </a>
          </div>
        </div>

      </div><!-- /tp-footer-top -->

      <!-- ── BOTTOM BAR ──────────────────────────────────────────────────── -->
      <div class="tp-footer-bottom">
        <span class="tp-footer-copy">&copy; <?= date('Y') ?> TourVerse</span>
        <span class="tp-footer-dot" aria-hidden="true">&bull;</span>
        <span class="tp-footer-powered">Powered by IBM watsonx.ai Granite</span>
        <span class="tp-footer-dot" aria-hidden="true">&bull;</span>
        <span class="tp-footer-credit">Developed by Harsh Rakeshkumar Champaneri</span>
      </div>

    </div>
  </footer>

  <!-- Bootstrap 5 JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <!-- App JS -->
  <script src="assets/js/app.js"></script>

</body>

</html>